# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassianlabs/docker-node-jdk-chrome-firefox

pipelines:
  default:
    - step:
        caches:
          - node
        deployment: test
        script: # Modify the commands below to build your repository.
          - npm install -g firebase-tools
          - npm install
          - npm run yalento:test:app
          - npm run yalento:test:api
          - npm run yalento:compile
          - npm run yalento:build:app
          - npm run yalento:build:functions
          - npm run yalento:compile
          - pipe: atlassian/firebase-deploy:0.3.8
            variables:
              FIREBASE_TOKEN: "$FIREBASE_TOKEN_CI"
              apiKey: "$apiKey"
              authDomain: "$authDomain"
              databaseURL: "$databaseURL"
              projectId: "$projectId"
              storageBucket: "$storageBucket"
              messagingSenderId: "$messagingSenderIdy"
              appId: "$appId"
              measurementId: "$measurementId"
